### PR TITLE
fix: read X-Forwarded-For for client IP in security audit events

### LINKED ISSUE #421: [Version: 3.11.0] Security events log proxy IP instead of client IP on Cloud Foundry
## Description

The `@cap-js/attachments` plugin extracts the client IP address for security event audit logging using `req.req?.socket?.remoteAddress` (https://github.com/cap-js/attachments/blob/main/lib/generic-handlers.js). On BTP Cloud Foundry (and any reverse-proxy deployment), this returns the internal IP of the Go Router or Approuter — not the actual client IP.

This affects all three security events:
- `AttachmentSizeExceeded`
- `AttachmentUploadRejected`
- `AttachmentDownloadRejected`

## Current behavior

```javascript
// lib/generic-handlers.js (3 occurrences)
const ipAddress = req.req?.socket?.remoteAddress
```

On CF, `socket.remoteAddress` resolves to the internal container/proxy IP (e.g., `10.x.x.x`), making the logged IP useless for security forensics.

## Expected behavior

The plugin should read `X-Forwarded-For` with fallback to `socket.remoteAddress`, consistent with how the Approuter extracts the client IP for audit logging:

```javascript
// @sap/approuter — lib/utils/logger.js:76
let IP = req.headers['x-forwarded-for'] || req.connection.remoteAddress;
```

### Context

- On BTP Cloud Foundry, the request chain is: `Client` → `Go Router` → `Approuter` → `Backend`. The `Go Router` sets `X-Forwarded-For` with the real client IP.
- `@cap-js/audit-logging` does not extract IP itself — it relies on the caller to provide the `ip` field, so the fix belongs in `@cap-js/attachments`.

### PR DESCRIPTION
**Pull request by cschuerings**
## Description

Fixes #421.

On reverse-proxy deployments (e.g. BTP Cloud Foundry), `socket.remoteAddress` returns the internal proxy/Go Router IP, not the real client IP. This makes the `ipAddress` field in security audit events (`AttachmentSizeExceeded`, `AttachmentUploadRejected`, `AttachmentDownloadRejected`) useless for security forensics.

## Changes

Read `X-Forwarded-For` first and fall back to `socket.remoteAddress` when the header is absent — consistent with how `@sap/approuter` resolves the client IP (`lib/utils/logger.js`):

```javascript
// before
const ipAddress = req.req?.socket?.remoteAddress

// after
const ipAddress = req.req?.headers?.["x-forwarded-for"] || req.req?.socket?.remoteAddress
```

The full `X-Forwarded-For` value is logged as-is (may be comma-separated when multiple proxies are in the chain). Falls back to `socket.remoteAddress` for direct connections without a proxy (e.g. local development).

### CODE REVIEW

File: lib/generic-handlers.js [hunk 1]
```diff
@@ -272,7 +274,8 @@ async function validateAttachmentSize(req, validateContentLength = false) {
     const attachmentRef = await SELECT.one("filename")
       .from(req.target)
       .where({ up__ID: req.data.up__ID })
-    const ipAddress = req.req?.socket?.remoteAddress
+    const ipAddress =
+      req.req?.headers?.["x-forwarded-for"] || req.req?.socket?.remoteAddress
```
Comment (KoblerS) [inline lib/generic-handlers.js]:
```suggestion
    const {ipAddress = req.req.ip
```

File: lib/generic-handlers.js [hunk 2]
```diff
@@ -330,7 +333,8 @@ function validateAttachmentMimeType(req) {
   const acceptableMediaTypes =
     req.target.elements.content["@Core.AcceptableMediaTypes"] || "*/*"
   if (!checkMimeTypeMatch(acceptableMediaTypes, mimeType)) {
-    const ipAddress = req.req?.socket?.remoteAddress
+    const ipAddress =
+      req.req?.headers?.["x-forwarded-for"] || req.req?.socket?.remoteAddress
```
Comment (KoblerS) [inline lib/generic-handlers.js]:
```suggestion
    const {ipAddress = req.req.ip
```

**Review by KoblerS — COMMENTED** [review]
According to https://expressjs.com/en/5x/api.html#req.ip req.ip should be set. Also verified locally using this example that this parameter is available:

```js
const express = require("express");
const app = express();
const PORT = 3000;

app.get("/", (req, res) => {
  console.log("Client IP:", req.ip);
  res.send(`Your IP is: ${req.ip}`);
});

app.listen(PORT, () => {
  console.log(`Server running on http://localhost:${PORT}`);
});
```

**Comment by cschuerings** [comment]
Thanks for checking! However, `req.ip` doesn't help here in a typical BTP/Cloud Foundry deployment with an approuter in front.

`req.ip` respects `trust proxy` — but in CF the app server doesn't (and shouldn't) set `app.set('trust proxy', true')`, because CAP doesn't configure this. Without that setting, Express leaves `req.ip` as the raw socket address.

I verified this with a deployed test app (approuter → Express server) that logs all three values. When switching between networks, `req.ip` and `socket.remoteAddress` always show the same internal/private IP of the last hop — while `X-Forwarded-For` correctly reflects the real client IP:

Network 1:
```json
"req.ip": "10.x.x.x",
"socket.remoteAddress": "10.x.x.x",
"x-forwarded-for": "203.x.x.x, 10.x.x.x, 52.x.x.x, 10.x.x.x"
```

Network 2 (different hotspot):
```json
"req.ip": "10.x.x.x",
"socket.remoteAddress": "10.x.x.x",
"x-forwarded-for": "80.x.x.x, 10.x.x.x, 52.x.x.x, 10.x.x.x"
```

The internal IPs stay constant regardless of which network the client is on, while the first entry in `X-Forwarded-For` changes correctly with the client's public IP. Reading `X-Forwarded-For` directly is therefore necessary to get the real client IP in this deployment topology.

**Review by schiwekM — APPROVED** [review]
Thanks for noticing and please excuse that I overlooked the approuter scenario in the initial impl.

**Comment by schiwekM** [comment]
Hi @cschuerings,
I adjusted the code to set `x-forwarded-for` as custom attribute on the audit log instead of using a different IP to avoid security problems as @KoblerS raised a valid concern that spoofing x-fowarded-for is far to easy. Furthermore the CF app can also directly be accessed in theory so the audit logging setup should not assume that access always happens via the approuter.

Is this a viable solution from your side as well?

**Comment by cschuerings** [comment]
> Hi @cschuerings, I adjusted the code to set `x-forwarded-for` as custom attribute on the audit log instead of using a different IP to avoid security problems as @KoblerS raised a valid concern that spoofing x-fowarded-for is far to easy. Furthermore the CF app can also directly be accessed in theory so the audit logging setup should not assume that access always happens via the approuter.
> 
> Is this a viable solution from your side as well?

Yes, this solution works for us.
Thank you for incorporating and adapting the fix!

**Review by KoblerS — APPROVED** [review]
