### PR TITLE
Attempting to PUT into non-existent entity should return 404

### LINKED ISSUE #297: [Version: 3.2.0] PUT content returns 204 when Attachment doesn't exist
**Describe the bug**
The plugin returns a successful status when calling PUT /content to a non-existent Attachment UUID.

Image

**To Reproduce**
The error needs to be reproduced on BTP with S3, as it doesn't happen with a local database.

1. Enable attachments on Books on a BTP bookshop service connected to S3.
2. Create a test.txt file with the content "test" (4 bytes).
3. Call PUT on a non-existent Attachment UUID:

>(service path)/Books_attachments(up__ID=999999,ID=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa)/content

The server responds with 204 No Content.
**Expected behavior**
If the entity doesn't exist, a 404 Not Found could be returned.

[ ] is it a regression issue? 

**Screenshots**

**Customer Info**
Company: SAP.

### PR DESCRIPTION
**Pull request by eric-pSAP**
Currently it returns a 204. Fixes #297

### CODE REVIEW

File: lib/aws-s3.js [hunk 1]
```diff
@@ -403,6 +407,10 @@ module.exports = class AWSAttachmentsService extends require("./basic") {
       }
     } else if (req?.data?.note) {
       const key = { ID: targetID }
+      if (!req.data.note) {
+        req.reject(404, "Attachment not found")
+        return
+      }
```
Comment (KoblerS) [inline lib/aws-s3.js]: is this really neccessary since we null check already in line 408?

File: lib/azure-blob-storage.js [hunk 2]
```diff
@@ -386,6 +390,10 @@ module.exports = class AzureAttachmentsService extends require("./basic") {
       }
     } else if (req?.data?.note) {
       const key = { ID: targetID }
+      if (!req.data.note) {
+        req.reject(404, "Attachment not found")
+        return
+      }
```
Comment (KoblerS) [inline lib/azure-blob-storage.js]: same question here.

File: lib/gcp.js [hunk 3]
```diff
@@ -373,6 +377,10 @@ module.exports = class GoogleAttachmentsService extends require("./basic") {
       }
     } else if (req?.data?.note) {
       const key = { ID: targetID }
+      if (!req.data.note) {
+        req.reject(404, "Attachment not found")
+        return
+      }
```
Comment (KoblerS) [inline lib/gcp.js]: same question here.

**Review by KoblerS — APPROVED** [review]
